"""fix version #2

Revision ID: 4e151088ee6f
Revises: 16c23f94b84c
Create Date: 2024-06-09 12:43:21.994724

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4e151088ee6f'
down_revision: Union[str, None] = '16c23f94b84c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_superuser', sa.Boolean(), nullable=False))
    op.add_column('user', sa.Column('is_verified', sa.Boolean(), nullable=False))
    op.drop_column('user', 'is superuser')
    op.drop_column('user', 'is verified')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is verified', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('user', sa.Column('is superuser', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('user', 'is_verified')
    op.drop_column('user', 'is_superuser')
    # ### end Alembic commands ###
